
CREATE TABLE IF NOT EXISTS music (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    mid TEXT NOT NULL UNIQUE,
    author TEXT,
    name TEXT NOT NULL,
    href TEXT,
    cover TEXT,
    lyc TEXT,
    music_url TEXT,
    local_path TEXT,
    duration_sec INTEGER DEFAULT 0,
    desc TEXT,

    status INTEGER DEFAULT 0,

    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kv_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key TEXT NOT NULL UNIQUE,
    value TEXT,
    expire_time INTEGER DEFAULT -1,
    status INTEGER DEFAULT 0,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS account (
    uid INTEGER PRIMARY KEY AUTOINCREMENT,
    account TEXT NOT NULL UNIQUE,
    password TEXT,
    nickname TEXT,
    remark TEXT,
    age TEXT,
    avater TEXT,
    desc TEXT,

    status INTEGER DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favor_ablum(
    aid INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    remark TEXT,
    cover TEXT,

    status INTEGER DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favor (
    fid INTEGER PRIMARY KEY AUTOINCREMENT,
    aid INTEGER,
    uid INTEGER,
    mid TEXT,
    remark TEXT,
    status INTEGER DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
